AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Change sets - Challenge (uksb-1q9p31idr) (tag:changesets).

Parameters:
  MyQueueName:
    Description: Name of the Amazon SQS queue you wish to create
    Type: String
    Default: mytestqueue

  BucketName:
    Description: Name of the Amazon S3 bucket you wish to create
    Type: String
    AllowedPattern: ^(?!(^xn--|.+-s3alias$))^[a-z0-9][a-z0-9-]{1,61}[a-z0-9]$
    ConstraintDescription: Bucket name can include numbers, lowercase letters, uppercase letters, periods (.), and hyphens (-). It cannot start or end with a hyphen (-).

Resources:
  NewS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  MySqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref MyQueueName

# - What do you think will happen if you create a new change set for the
#   cfn-workshop-understanding-changesets stack using the changeset-challenge.yaml file?
# - How many resources will be added? Will any resource be removed?
# - Will you be able to get the physical ID of the queue from the JSON changes of the change set?

# - It will detect a new resource to be created
# - 2 new resource will be created: one for new SQS queue and one for S3 bucket because we changed the name of the resource from `MyS3Bucket` to `NewS3Bucket`
# - Cannot get the ID of the queue 




