AWSTemplateFormatVersion: "2010-09-09"

Description: AWS CloudFormation workshop - Conditions at property level

# Add your code here!

Parameters:
  EnvType:
    Type: String
    AllowedValues:
      - test
      - prod
    Default: test
    Description: The env to use
  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Conditions:
  IsProd: !Equals
    - !Ref EnvType
    - prod

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro

  Volume:
    Type: AWS::EC2::Volume
    Condition: IsProd
    Properties:
      Size: 2
      AvailabilityZone: !GetAtt EC2Instance.AvailabilityZone
      Encrypted: true
  
  MountPoint:
    Type: AWS::EC2::VolumeAttachment
    Condition: IsProd
    Properties:
      VolumeId: !Ref Volume
      InstanceId: !Ref EC2Instance
      Device: /dev/sdh

Outputs:
  LogicalId:
    Condition: IsProd
    Value: !GetAtt EC2Instance.PublicIp