AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation workshop - Dynamic references - EC2 template
Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Select ['0', !GetAZs ""]
      InstanceType: 't2.micro'
      ImageId: '{{resolve:ssm:/images/amazon-linux-2}}'